// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_42a0a9061e19377b, []int{0}
}
func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (dst *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(dst, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type InfoUser struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PhotoUUID            string   `protobuf:"bytes,3,opt,name=photoUUID,proto3" json:"photoUUID,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoUser) Reset()         { *m = InfoUser{} }
func (m *InfoUser) String() string { return proto.CompactTextString(m) }
func (*InfoUser) ProtoMessage()    {}
func (*InfoUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_42a0a9061e19377b, []int{1}
}
func (m *InfoUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoUser.Unmarshal(m, b)
}
func (m *InfoUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoUser.Marshal(b, m, deterministic)
}
func (dst *InfoUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoUser.Merge(dst, src)
}
func (m *InfoUser) XXX_Size() int {
	return xxx_messageInfo_InfoUser.Size(m)
}
func (m *InfoUser) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoUser.DiscardUnknown(m)
}

var xxx_messageInfo_InfoUser proto.InternalMessageInfo

func (m *InfoUser) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *InfoUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InfoUser) GetPhotoUUID() string {
	if m != nil {
		return m.PhotoUUID
	}
	return ""
}

func (m *InfoUser) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type SessionToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionToken) Reset()         { *m = SessionToken{} }
func (m *SessionToken) String() string { return proto.CompactTextString(m) }
func (*SessionToken) ProtoMessage()    {}
func (*SessionToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_42a0a9061e19377b, []int{2}
}
func (m *SessionToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionToken.Unmarshal(m, b)
}
func (m *SessionToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionToken.Marshal(b, m, deterministic)
}
func (dst *SessionToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionToken.Merge(dst, src)
}
func (m *SessionToken) XXX_Size() int {
	return xxx_messageInfo_SessionToken.Size(m)
}
func (m *SessionToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionToken.DiscardUnknown(m)
}

var xxx_messageInfo_SessionToken proto.InternalMessageInfo

func (m *SessionToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SessionPayload struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionPayload) Reset()         { *m = SessionPayload{} }
func (m *SessionPayload) String() string { return proto.CompactTextString(m) }
func (*SessionPayload) ProtoMessage()    {}
func (*SessionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_42a0a9061e19377b, []int{3}
}
func (m *SessionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionPayload.Unmarshal(m, b)
}
func (m *SessionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionPayload.Marshal(b, m, deterministic)
}
func (dst *SessionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionPayload.Merge(dst, src)
}
func (m *SessionPayload) XXX_Size() int {
	return xxx_messageInfo_SessionPayload.Size(m)
}
func (m *SessionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SessionPayload proto.InternalMessageInfo

func (m *SessionPayload) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*UserID)(nil), "models.UserID")
	proto.RegisterType((*InfoUser)(nil), "models.InfoUser")
	proto.RegisterType((*SessionToken)(nil), "models.SessionToken")
	proto.RegisterType((*SessionPayload)(nil), "models.SessionPayload")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	GetUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*InfoUser, error)
	GetSessionInfo(ctx context.Context, in *SessionToken, opts ...grpc.CallOption) (*SessionPayload, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*InfoUser, error) {
	out := new(InfoUser)
	err := c.cc.Invoke(ctx, "/models.Auth/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetSessionInfo(ctx context.Context, in *SessionToken, opts ...grpc.CallOption) (*SessionPayload, error) {
	out := new(SessionPayload)
	err := c.cc.Invoke(ctx, "/models.Auth/GetSessionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	GetUserByID(context.Context, *UserID) (*InfoUser, error)
	GetSessionInfo(context.Context, *SessionToken) (*SessionPayload, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Auth/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetUserByID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetSessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetSessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Auth/GetSessionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetSessionInfo(ctx, req.(*SessionToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByID",
			Handler:    _Auth_GetUserByID_Handler,
		},
		{
			MethodName: "GetSessionInfo",
			Handler:    _Auth_GetSessionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_42a0a9061e19377b) }

var fileDescriptor_auth_42a0a9061e19377b = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56, 0x92,
	0xe0, 0x62, 0x0b, 0x2d, 0x4e, 0x2d, 0xf2, 0x74, 0x11, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb2, 0x94, 0x72, 0xb8, 0x38, 0x3c, 0xf3, 0xd2, 0xf2, 0x41,
	0xb2, 0xe8, 0x72, 0x42, 0x52, 0x5c, 0x1c, 0xa5, 0x40, 0xf1, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26,
	0xa0, 0x28, 0x67, 0x10, 0x9c, 0x2f, 0x24, 0xc3, 0xc5, 0x59, 0x90, 0x01, 0xb4, 0x22, 0x34, 0x14,
	0xa8, 0x85, 0x19, 0x2c, 0x89, 0x10, 0x10, 0x12, 0xe3, 0x62, 0x4b, 0x4c, 0x2e, 0xc9, 0x2c, 0x4b,
	0x95, 0x60, 0x01, 0x4a, 0x71, 0x04, 0x41, 0x79, 0x4a, 0x2a, 0x5c, 0x3c, 0xc1, 0xa9, 0xc5, 0xc5,
	0x99, 0xf9, 0x79, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x42, 0x22, 0x5c, 0xac, 0x25, 0x20, 0x06, 0xd8,
	0x52, 0xce, 0x20, 0x08, 0x47, 0x49, 0x81, 0x8b, 0x0f, 0xaa, 0x2a, 0x20, 0xb1, 0x32, 0x27, 0x3f,
	0x31, 0x05, 0xdd, 0x65, 0x46, 0xe5, 0x5c, 0x2c, 0x8e, 0x40, 0x5f, 0x0a, 0xe9, 0x73, 0x71, 0xbb,
	0xa7, 0x96, 0x80, 0x1c, 0xef, 0x54, 0x09, 0xf2, 0x9c, 0x1e, 0xc4, 0xbf, 0x7a, 0x10, 0xcf, 0x4a,
	0x09, 0xc0, 0xf8, 0x70, 0x2f, 0xda, 0x71, 0xf1, 0x01, 0x35, 0x40, 0x4d, 0x07, 0x89, 0x0a, 0x89,
	0xc0, 0xd4, 0x20, 0x3b, 0x4c, 0x4a, 0x0c, 0x4d, 0x14, 0xea, 0x90, 0x24, 0x36, 0x70, 0xb8, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xa7, 0x0e, 0x4d, 0x65, 0x01, 0x00, 0x00,
}
